GET https://dmaz11xve5.execute-api.eu-central-1.amazonaws.com/dev/icalendar

# Weather API
###
GET https://api.openweathermap.org/data/2.5/forecast?id=3077916&APPID={{weather-api-key}}&lang=cz&units=metric